### ISSUE TITLE
Need Local Saving Database

### ISSUE THREAD

**Issue by libertesedamatrix** [fabriciocaetano/lil#1]
Can you add local database to save the learn of bot without allow another AI agressive comunicate with the bot?

**Comment by fabriciocaetano** [comment]
perfeitamente que sim, porém esta parte não foi automatizada para alterações, para alterações manuais, vá para a pasta nltk_data em sua pasta home, onde há bancos de dados separados pré treinados, porém, a configuração inicial padrão está dentro do próprio código do bot, mas para usar uma base externa de treinamento e carregamento basta substituir as linhas de conversas por diretórios locais. algo que ainda erá explicado mais para frente sem data de  atualização.
